import fs from 'fs/promises';
import path from 'path';

const TEMPLATES: Record<string, string> = {
  web: `
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1-v2 build dev cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Next.js build output
.next/
out/

# Production build
build/
dist/

# Env files
.env*.local
.env

# OS files
.DS_Store
Thumbs.db
  `,
  unity: `
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Cc]onfighooks/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# Asset meta files must be tracked
!/[Aa]ssets/**/*.meta

# Autogenerated JetBrains Rider project files
.idea/ProjectSettings/RiderScriptEditorPersist.ads

# VS/vscode
.vscode/
.vs/
*.csproj
*.sln
*.unitypackage
*.user
*.userprefs

# OS files
.DS_Store
Thumbs.db
  `,
  generic: `
# OS Files
.DS_Store
Thumbs.db
*.tmp
*.bak
*.swp

# Build artifacts
dist/
build/
out/
bin/
obj/

# Logs
*.log
  `
};

class GitignoreService {
  async generate(projectPath: string, type: string = 'generic'): Promise<void> {
    const template = TEMPLATES[type] || TEMPLATES.generic;
    const filePath = path.join(projectPath, '.gitignore');
    await fs.writeFile(filePath, template.trim());
  }

  async read(projectPath: string): Promise<string> {
    const filePath = path.join(projectPath, '.gitignore');
    try {
      return await fs.readFile(filePath, 'utf8');
    } catch (e) {
      return '';
    }
  }

  async save(projectPath: string, content: string): Promise<void> {
    const filePath = path.join(projectPath, '.gitignore');
    await fs.writeFile(filePath, content);
  }
}

export const gitignoreService = new GitignoreService();
